version: '3.3'
services:
  data-science:
    build: 
      context: ./docker
    image: shivangi/coronavirus_dashboard
    ports:
      - "8888:8888"
    volumes:
      - ./code/:/home/jovyan/work/code/